version: 2
jobs:
  build:
    docker: 
      - image: circleci/node 
    steps:
      - checkout
      - run
        command: | 
          echo "You can even have multiline commands."
      - restore_cache:
        keys: 
        command: | 
            mkdir ~/cache/
      - run: 
        command: | 
          echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths: ~/cache
