version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master #Should only run on Master Branch
      - test-production:
          requires:
            - build
          filters:
            branches:
              only: master #Should only run on Master Branch
      - deploy:
          requires:
            - test-production
          filters:
            branches:
              only: Production #Should run on new branch
