version: 2.1

branches:  # Pipelines that run automatically on a commit to a branch
  production:
    - step:
        script:
            - echo "Extra proof that this is the Production branch!"
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test-production:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test-production:
          requires:
            - build
      - deploy:
          requires:
            - test-production
          only:
            refs:
              - production
